### ISSUE TITLE
Minecraft Server Status Applet

### ISSUE THREAD

**Issue by Baa14453** [DasKeyboard/q-marketplace#20]
Hi,
I made an applet that monitors the status of Minecraft Servers and lights up keys depending on whether it's online and how player players have joined: https://github.com/Baa14453/daskeyboard-applet-minecraft-server-status

**Comment by Mubramaj** [comment]
Hi,

Nice applet, I think many people will like it. Thank you for contributing.

I already started the review and here is the first feedback:

- [x] Our requirement is for the index.js to not be mimified
- [ ] We need some tests, there is examples on other applets like this one https://github.com/daskeyboard/daskeyboard-applet--github/tree/master/test but you can explore more applets. We advice to use mocha.
- [x] I cannot see the 'minecraft-protocol' in the package.json dependencies

**Comment by Baa14453** [comment]
Hi Mubramaj,
I've switched libraries so it's a lot simpler now and removed the minification
I'll look at the tests later in the week hopefully

**Comment by Baa14453** [comment]
Tests are in @Mubramaj :+1:

**Comment by Baa14453** [comment]
:eyes:

**Comment by Mubramaj** [comment]
Hi @Baa14453 ,

I am sorry for this late reply. The new changes looks really good. Just some last feedback for it to be perfect:

- [ ] https://github.com/Baa14453/daskeyboard-applet-minecraft-server-status/blob/master/README_ENDUSER.md Looks like this one is out of date, referring to Youtube
- [ ] All your git links are pointing to gitlab instead of github. 
- [ ] Did you double check the package.json I see 'Legitcorp' as a publisher instead of you 
- [ ] changelog file is also out of date. You can empty it, I will populate it once I release your applet
- [ ] For the tests I think you should focus on your 'getSignal' method. Mocking the 'getStatus' method and expect several outputs depending on your mock. There is an example in this applet https://github.com/daskeyboard/daskeyboard-applet--stack-overflow/blob/master/test/test.js

**Comment by Baa14453** [comment]
Hi @Mubramaj thanks for your help, see my latest commits please

- Youtube references are fixed thanks
- Gitlab is the correct location, this is mirrored to Github for convenience.
- Legitcorp is myself, I run the website and Gitlab.
- Changelog emptied thanks
- I've improved on the tests, it now checks a few scenarios and checks if the button colours are in the right places.
- Added better pictures
- Proper handling for when a server goes offline (before the keys would just stay as their last command).

Two things I wasn't able to do and could use some guidance with:
- I've added default origins to the package.json but they don't seem to be picked up in the Daskey software, not sure if my format is wrong. See [here.](https://github.com/Baa14453/daskeyboard-applet-minecraft-server-status/blob/master/package.json#L43)
- When the server goes offline I'd like to revert most of the points to the default, from before I changed them so they are back to whatever RGB profile the user had. I tried setting the key as `#000000` (this just turned it off) and `#FFFFFF` (this turned it white) and even `#00000000` to set transparency but none were successful, is there a way I can do this?

**Comment by Baa14453** [comment]
:eyes:

**Comment by Mubramaj** [comment]
Hi @Baa14453 ,

I am sorry for the late reply

- We don't handle the default origin for now that's why it's not picked up by the software
- There is no way on the API to revert back to profile color for now. The user needs to clear the key or you can ask default background color on your applet setting and the applet reverts back to this default background color.



I will publish a first version of your Applet since it is ready. You can make this improvements later with the default background color settings or once we implement an API feature that allows you to clear back to the background color.

**Comment by Mubramaj** [comment]
Hi again,

I was testing your applet following this guide https://www.daskeyboard.io/applet-development/ section `Loading Dev applet into Q Desktop` and when I configure the applet with a server that is not running I get redirected to the applet questions page without any error message. 
Can you also provide me an address and a valid port to test the applet ( I don't have any minecraft server)

To see how to handle errors on the question page you can take a look at the `applyConfig` method of this applet https://github.com/daskeyboard/daskeyboard-applet--firewall-guard

Best

**Comment by Baa14453** [comment]
Hi Mumbraj, I'll check it out soon, in the meantime feel free to use `legitcorp.com` as a server address to test with, use the default port of 25565

**Comment by Baa14453** [comment]
Mubramaj it shouldn't matter whether your configured server is offline or not, I can add my applet with any IP address and port, if the server is offline the keys will show-up as all red which is intended.

Mine doesn't redirect me back to any text input area but it does remain on the configuration page like this:

![image](https://user-images.githubusercontent.com/9057997/208192591-4a402ecc-5ebd-4585-8f7e-5b72e6cd43db.png)

In the guide the gif shows a message saying the applet was added successfully but this doesn't appear for me with any applet I add so maybe the guide is just outdated?

![image](https://user-images.githubusercontent.com/9057997/208192825-46cda15d-b86a-434e-8e16-a0663d446cc8.png)

**Comment by Baa14453** [comment]
Hi Mubramaj, I've added your proposed changes in the PR and also pushed some additional fixes, tests should work now I was missing a field.

**Comment by Baa14453** [comment]
Did some more cleaning today, Readme reads better in daskeyboard, the ENDUSER readme didn't work at all because I'd used URL references instead of file references for some reason so those are all fixed

**Comment by Mubramaj** [comment]
Hi @Baa14453 ,

I am sorry, I updated our fork today https://github.com/daskeyboard/daskeyboard-applet--minecraft-server-status/tree/master with your last changes but I still cannot run the applet.

![image](https://user-images.githubusercontent.com/20217427/208467941-042469de-b8b8-4428-96c7-bc1ee22cb8cc.png)

Can you tell me what IP you use for it to work ? I used legitcorp and the default `192.168.1.10` and same result each time, I cannot pass through the configuration

**Comment by Baa14453** [comment]
@Mubramaj Just tried it in a virtual machine to see what's going on, it doesn't work until I run `yarn` manually to install the dependencies is that normal? Not sure how other applets handle dependency installation for the end user

**Comment by fabiendv** [comment]
@Baa14453 I made some changes. Can you update your repo?

Your applet will be live soon enough. 

Thank you.
